language: android
sudo: enabled
jdk: oraclejdk8
script: "./gradlew build"
android:
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
deploy:
  provider: releases
  file_glob: true
  file: "/home/travis/build/zoxal/7ate9-client/app/build/outputs/apk/release/7ate9-client*"
  skip_cleanup: true
  overwrite: true
  on:
    repo: zoxal/7ate9-client
    tags: true
before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
- ./gradlew dependencies || true
- openssl aes-256-cbc -K $encrypted_7fc8947abd05_key -iv $encrypted_7fc8947abd05_iv
  -in keystore-config.enc -out keystore-config -d
- tar xvf keystore-config
