language: android
sudo: enabled
jdk: oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_7fc8947abd05_key -iv $encrypted_7fc8947abd05_iv
  -in secure-data.enc -out secure-data.tar -d
- tar xvf secure-data.tar
- mkdir "$ANDROID_HOME/licenses" || true
- cp android-sdk-license "$ANDROID_HOME/licenses/android-sdk-license"
- chmod +x gradlew
- "./gradlew dependencies || true"
script: "./gradlew build"
android:
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
deploy:
  provider: releases
  api_key:
    secure: "neuB9IARJ18Yi/MPEdvj+/ZeZ8XcKXqrD8azPcv80bvy+IJVolQ3Yz/kcijqhrPsbQHNVzz4lHSHGLBpZmfaKBnRigFjjY1QjbjLvr/QurvwvFkqZJavFe5Y4E34g4SKKK15jXmDdMmXESfzO/GQdNNha2l5ACxNBsWQtSWSFoFnxdm4S3edEfE++SV/7//DJ4fHMcGw7gByhL3o3ORffh80UYmqh1I/bJo2mT2J6gh01+9YLAepjoo/jasQDDXUWwPiOONboot1tAkCpKPM9Uyux2helosS33DMCNqoySfyHkYmX7tl+0j0G/zkyViFwkGhjfBK5LG0uO80vJJ3qdEFp8+0xP3fMzkFgAglIIpZprdJOf5bhMNL3UK/2N7aB4gC8BR/ub/trALcpdq6z6Yy5u5KsrjLgp3lZAQsGSajb3CSh9OhjFlOMxZRLsf2p8TOqhsEQvBFmr1VR7uUgOx/gRnJ4A/E7xdpVxMWJdxFCbHtUboSBROGD2lRNKof95Tlsz7ZHO1VIVaQyHeJAK37kRSPi5ubtEEboXg2cuagozcbv3vElB6vxZ5mlTg4EtrzcVo/QS3/k/e72NBtq/5CNG6HW2ZrOHgXNLJKpjEqaIb1FNpOZAmliy/PS1mDsswhibenF2nBKAfPfh9cGpc4W/R5zD6BgkW5jIqBPRk="
  file_glob: true
  file: "/home/travis/build/zoxal/7ate9-client/app/build/outputs/apk/release/7ate9-client*"
  skip_cleanup: true
  overwrite: true
  on:
    repo: zoxal/7ate9-client
    tags: true