language: android
sudo: enabled
jdk: oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_7fc8947abd05_key -iv $encrypted_7fc8947abd05_iv
  -in secure-data.enc -out secure-data -d
- tar xvf secrets.tar
- mkdir "$ANDROID_HOME/licenses" || true
- cp android-sdk-license "$ANDROID_HOME/licenses/android-sdk-license"
- chmod +x gradlew
- "./gradlew dependencies || true"
script: "./gradlew build"
android:
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
deploy:
  provider: releases
  file_glob: true
  file: "/home/travis/build/zoxal/7ate9-client/app/build/outputs/apk/release/7ate9-client*"
  skip_cleanup: true
  overwrite: true
  on:
    repo: zoxal/7ate9-client
    tags: true